import type { Metadata } from 'next'
import Link from 'next/link'
import { QrCode } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'FlickQR Terms of Service — the rules for using our free QR code generator.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border px-6 py-4">
        <Link href="/" className="flex items-center gap-2 w-fit">
          <div className="w-8 h-8 rounded-lg bg-primary/20 flex items-center justify-center">
            <QrCode className="w-5 h-5 text-primary" />
          </div>
          <span className="text-xl font-semibold text-foreground">FlickQR</span>
        </Link>
      </nav>
      <main className="max-w-2xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-10 text-sm">Last updated: April 2025</p>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Using FlickQR</h2>
            <p>FlickQR is a free QR code generation tool. By using it, you agree to use it only for lawful purposes. You may use QR codes generated by FlickQR for personal or commercial purposes.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Prohibited uses</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>Generating QR codes that link to malicious, illegal, or harmful content</li>
              <li>Using FlickQR for phishing, fraud, or deception</li>
              <li>Attempting to reverse-engineer or scrape the service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Disclaimer</h2>
            <p>FlickQR is provided &quot;as is&quot; without warranty of any kind. We are not responsible for how QR codes generated on our platform are used or for any damages arising from use of the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Changes</h2>
            <p>We may update these terms at any time. Continued use of FlickQR after changes constitutes acceptance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">Contact</h2>
            <p>Questions? Reach us on WhatsApp: <a href="https://wa.me/918076720669" className="text-primary hover:underline">+91 80767 20669</a></p>
          </section>
        </div>

        <div className="mt-12">
          <Link href="/" className="text-primary hover:underline text-sm">← Back to FlickQR</Link>
        </div>
      </main>
    </div>
  )
}
